### ISSUE TITLE
Typescript generation has failed

### ISSUE THREAD

**Issue by mheffner** [getmacroscope/aws-pricing#47]
Something in the Typescript generation has broken. When running tests on master I'm seeing the following. The `_1` suffix seems to imply a typescript import [issue](https://github.com/microsoft/TypeScript/issues/50036):

```
Running in dev mode.
Exception: "context_1" is not defined. [
  { lineNumber: 16 },
  { lineNumber: 11 },
  { function: 'runAllTests', lineNumber: 15 }
]
ReferenceError
```

**Comment by mheffner** [comment]
https://github.com/google/clasp/issues/947

**Comment by niels4** [comment]
I have a fix for this with PR #50 

The Google Apps Script "module system" is weird. It seems to just dump all of the exports into the global scope and then comment out the import statements. This mostly works except there are a few cases where GAS bundler doesn't play well with the typescript compiler. When importing a plain function, the typescript compiler will attach it to a temporary object, GAS bundler is unaware of this when it comments out the import statement. Then when the function is called later, it tries to reference the temporary object that isn't there, resulting in the `context_1` is undefined error.

To fix this I simply wrapped any function that was being exported in an object. The typescript compiler no longer creates temporary objects and the GAS imports work correctly.

Now the app will run until it hits this error mentioned in Issue #46 "Pricing look ups fail with DNS ERROR "

**Comment by mheffner** [comment]
Nice @niels4, that's great to hear you were able to figure it out!

**Comment by niels4** [comment]
![GAS_imports](https://user-images.githubusercontent.com/4206033/203153800-35b523dc-b472-4031-8a6f-136ba05c78bb.png)

**Comment by niels4** [comment]
It was no problem. The trickiest part was trying to wrap my head around how the whole GAS ecosystem works. Just figuring out how to deploy and run the debugger was a bit of a pain. The developer docs you wrote were a big help in started and guiding me in the right direction.
