### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by ZeleniJure** [getmacroscope/aws-pricing#48]
I just installed the addon to try it out, and I keep getting DNS errors. This is what I have tried:
- new settings sheet command
- show manual command
- RDS_POSTGRESQL calculation

In all cases I get: `DNS error: https://a0.p.awsstatic.com/pricing/1.0/ec2/manifest.json?timestamp=1666872873866 (line 24).`

This is the installed version: `Listing updated:May 13, 2022`

**Comment by mheffner** [comment]
Hi @ZeleniJure , thanks for writing in and I apologize that this isn't working for you. We are currently blocked by the issue in https://github.com/mheffner/aws-pricing/issues/46

**Comment by krayjay** [comment]
Someone has made a pull request that allegedly fixes this issue, please push!

**Comment by aryounce** [comment]
@krayjay I'm closing this issue as we're testing the restored add-on and dealing with a few lingering errors. This will be addressed along with some other issues when we close #46.
